# Generated by Django 6.1 on 2026-08-11 07:29

import django.core.validators
import django.db.models.deletion
import feincms3.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["position"],
                "verbose_name": "page",
                "verbose_name_plural": "pages",
            },
        ),
        migrations.AlterField(
            model_name="image",
            name="alternative_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the contents, e.g. for screenreaders.",
                max_length=1000,
                verbose_name="alternative text",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                height_field="height",
                upload_to=feincms3.utils.upload_to,
                verbose_name="image",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="pages.page",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="language_code",
            field=models.CharField(
                choices=[("", "")], default="en", max_length=10, verbose_name="language"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="menu",
            field=models.CharField(
                blank=True,
                choices=[("", "")],
                default="main",
                max_length=100,
                verbose_name="menu",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[("", "")],
                default="standard",
                max_length=100,
                verbose_name="page type",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="Automatically generated by concatenating the parent's path and the slug unless the path is defined manually.",
                max_length=1000,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Path must start and end with a slash (/).",
                        regex="^/(|.+/)$",
                    )
                ],
                verbose_name="path",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="page",
            name="static_path",
            field=models.BooleanField(
                default=False, verbose_name="manually define the path"
            ),
        ),
        migrations.AlterField(
            model_name="richtext",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="pages.page",
            ),
        ),
    ]
