# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 11:25
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
import feincms3.cleanse
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is active"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(
                        unique_for_year="publication_date", verbose_name="slug"
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="publication date",
                    ),
                ),
                ("body", feincms3.cleanse.CleansedRichTextField(verbose_name="body")),
                (
                    "category",
                    models.CharField(
                        choices=[("blog", "blog"), ("publications", "publications")],
                        db_index=True,
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "ordering": ["-publication_date"],
                "get_latest_by": "publication_date",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagefield.fields.ImageField(
                        height_field="height",
                        upload_to="images/%Y/%m",
                        verbose_name="image",
                        width_field="width",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="image width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="image height",
                    ),
                ),
                (
                    "ppoi",
                    imagefield.fields.PPOIField(
                        default="0.5x0.5",
                        max_length=20,
                        verbose_name="primary point of interest",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="caption"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="articles.Article",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "abstract": False,
                "verbose_name_plural": "images",
            },
        ),
    ]
