# Generated by Django 6.1 on 2026-08-11 07:29

import feincms3.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="alternative_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the contents, e.g. for screenreaders.",
                max_length=1000,
                verbose_name="alternative text",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                height_field="height",
                upload_to=feincms3.utils.upload_to,
                verbose_name="image",
                width_field="width",
            ),
        ),
    ]
